// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using maildot.Data;
using maildot.Models;

#nullable disable

namespace maildot.Data.Migrations
{
    [DbContext(typeof(MailDbContext))]
    [Migration("20251212110000_AddSenderLabels")]
    partial class AddSenderLabels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("maildot.Models.ImapAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("imap_accounts", (string)null);
                });

            modelBuilder.Entity("maildot.Models.ImapFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("LastUid")
                        .HasColumnType("bigint")
                        .HasColumnName("last_uid");

                    b.Property<string>("SyncToken")
                        .HasColumnType("text");

                    b.Property<long?>("UidValidity")
                        .HasColumnType("bigint")
                        .HasColumnName("uid_validity");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "FullName")
                        .IsUnique();

                    b.ToTable("imap_folders", (string)null);
                });

            modelBuilder.Entity("maildot.Models.ImapMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FolderId")
                        .HasColumnType("integer");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ImapUid")
                        .HasColumnType("bigint");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FolderId", "ImapUid")
                        .IsUnique();

                    b.HasIndex("ReceivedUtc");

                    b.ToTable("imap_messages", (string)null);
                });

            modelBuilder.Entity("maildot.Models.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentLabelId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_label_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ParentLabelId");

                    b.HasIndex("AccountId", "ParentLabelId", "Name")
                        .IsUnique();

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("maildot.Models.MessageAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disposition")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LargeObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("large_object_id");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("message_attachments", (string)null);
                });

            modelBuilder.Entity("maildot.Models.MessageBody", b =>
                {
                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, string[]>>("Headers")
                        .HasColumnType("jsonb");

                    b.Property<string>("HtmlText")
                        .HasColumnType("text");

                    b.Property<string>("PlainText")
                        .HasColumnType("text");

                    b.Property<string>("Preview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SanitizedHtml")
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.ToTable("message_bodies", (string)null);
                });

            modelBuilder.Entity("maildot.Models.MessageEmbedding", b =>
                {
                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("halfvec(1024)");

                    b.HasKey("MessageId", "ChunkIndex");

                    b.ToTable("message_embeddings", (string)null);
                });

            modelBuilder.Entity("maildot.Models.MessageLabel", b =>
                {
                    b.Property<int>("LabelId")
                        .HasColumnType("integer");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.HasKey("LabelId", "MessageId");

                    b.HasIndex("LabelId");

                    b.HasIndex("MessageId");

                    b.ToTable("message_labels", (string)null);
                });

            modelBuilder.Entity("maildot.Models.SenderLabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_address");

                    b.Property<int>("LabelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromAddress");

                    b.HasIndex("LabelId");

                    b.ToTable("sender_labels", (string)null);
                });

            modelBuilder.Entity("maildot.Models.ImapFolder", b =>
                {
                    b.HasOne("maildot.Models.ImapAccount", "Account")
                        .WithMany("Folders")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("maildot.Models.ImapMessage", b =>
                {
                    b.HasOne("maildot.Models.ImapFolder", "Folder")
                        .WithMany("Messages")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("maildot.Models.Label", b =>
                {
                    b.HasOne("maildot.Models.ImapAccount", "Account")
                        .WithMany("Labels")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("maildot.Models.Label", "ParentLabel")
                        .WithMany("Children")
                        .HasForeignKey("ParentLabelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");

                    b.Navigation("ParentLabel");
                });

            modelBuilder.Entity("maildot.Models.MessageAttachment", b =>
                {
                    b.HasOne("maildot.Models.ImapMessage", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("maildot.Models.MessageBody", b =>
                {
                    b.HasOne("maildot.Models.ImapMessage", "Message")
                        .WithOne("Body")
                        .HasForeignKey("maildot.Models.MessageBody", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("maildot.Models.MessageEmbedding", b =>
                {
                    b.HasOne("maildot.Models.ImapMessage", "Message")
                        .WithMany("Embeddings")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("maildot.Models.MessageLabel", b =>
                {
                    b.HasOne("maildot.Models.Label", "Label")
                        .WithMany("MessageLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("maildot.Models.ImapMessage", "Message")
                        .WithMany("LabelLinks")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("maildot.Models.SenderLabel", b =>
                {
                    b.HasOne("maildot.Models.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");
                });

            modelBuilder.Entity("maildot.Models.ImapAccount", b =>
                {
                    b.Navigation("Labels");

                    b.Navigation("Folders");
                });

            modelBuilder.Entity("maildot.Models.ImapFolder", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("maildot.Models.ImapMessage", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Embeddings");

                    b.Navigation("LabelLinks");
                });

            modelBuilder.Entity("maildot.Models.Label", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MessageLabels");
                });
#pragma warning restore 612, 618
        }
    }
}
