// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using maildot.Data;

#nullable disable

namespace maildot.Data.Migrations
{
    [DbContext(typeof(MailDbContext))]
    partial class MailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("maildot.Models.ImapAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("imap_accounts", (string)null);
                });

            modelBuilder.Entity("maildot.Models.ImapFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("LastUid")
                        .HasColumnType("bigint")
                        .HasColumnName("last_uid");

                    b.Property<string>("SyncToken")
                        .HasColumnType("text");

                    b.Property<long?>("UidValidity")
                        .HasColumnType("bigint")
                        .HasColumnName("uid_validity");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("imap_folders", (string)null);
                });

            modelBuilder.Entity("maildot.Models.ImapMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FolderId")
                        .HasColumnType("integer");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, string[]>>("Headers")
                        .HasColumnType("jsonb");

                    b.Property<long>("ImapUid")
                        .HasColumnType("bigint");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FolderId", "ImapUid")
                        .IsUnique();

                    b.ToTable("imap_messages", (string)null);
                });

            modelBuilder.Entity("maildot.Models.MessageAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LargeObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("large_object_id");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("message_attachments", (string)null);
                });

            modelBuilder.Entity("maildot.Models.MessageBody", b =>
                {
                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<string>("HtmlText")
                        .HasColumnType("text");

                    b.Property<string>("PlainText")
                        .HasColumnType("text");

                    b.Property<string>("Preview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SanitizedHtml")
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.ToTable("message_bodies", (string)null);
                });

            modelBuilder.Entity("maildot.Models.MessageEmbedding", b =>
                {
                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.HasKey("MessageId", "ChunkIndex");

                    b.ToTable("message_embeddings", (string)null);
                });

            modelBuilder.Entity("maildot.Models.ImapFolder", b =>
                {
                    b.HasOne("maildot.Models.ImapAccount", "Account")
                        .WithMany("Folders")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("maildot.Models.ImapMessage", b =>
                {
                    b.HasOne("maildot.Models.ImapFolder", "Folder")
                        .WithMany("Messages")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("maildot.Models.MessageAttachment", b =>
                {
                    b.HasOne("maildot.Models.ImapMessage", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("maildot.Models.MessageBody", b =>
                {
                    b.HasOne("maildot.Models.ImapMessage", "Message")
                        .WithOne("Body")
                        .HasForeignKey("maildot.Models.MessageBody", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("maildot.Models.MessageEmbedding", b =>
                {
                    b.HasOne("maildot.Models.ImapMessage", "Message")
                        .WithMany("Embeddings")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("maildot.Models.ImapAccount", b =>
                {
                    b.Navigation("Folders");
                });

            modelBuilder.Entity("maildot.Models.ImapFolder", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("maildot.Models.ImapMessage", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Embeddings");
                });
#pragma warning restore 612, 618
        }
    }
}
